spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: "root"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
